Project/OODWebsite/OODWebsite/Areas/QuanLyHeThong/Controllers/QuanLyNV_GDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OODWebsite.Areas.QuanLyHeThong.Controllers
{
    public class QuanLyNV_GDController : Controller
    {
        PortalDBDataContext context = new PortalDBDataContext();
        // GET: QuanLyHeThong/QuanLyNV_GD
        public ActionResult QuanLyNV_GD()
        {
            var nv = context.NVPDTs.ToList();
            return View(nv);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Exclude = "Id")] NVPDT nv)
        {
            if (nv.TenNV != null && nv.GioiTinh != null && nv.email != null && nv.Matkhau != null)
            {
                context.NVPDTs.InsertOnSubmit(nv);
                context.SubmitChanges();
                return RedirectToAction(nameof(QuanLyNV_GD));
            }
            ModelState.AddModelError("", "Thông tin nhập bị thiếu");
            return View();
        }

        public ActionResult Edit(int id)
        {
            var nv = context.NVPDTs.ToList().Find(m => m.MaNV == id);
            return View(nv);
        }

     
        [HttpPost]
        public ActionResult Edit(NVPDT nv)
        {
            var data = context.NVPDTs.ToList().Find(m => m.MaNV == nv.MaNV);
            if (nv.TenNV == null || nv.GioiTinh == null || nv.email == null || nv.Matkhau == null)
            {
                ModelState.AddModelError("", "Thông tin nhập bị thiếu");
                return View(nv);
            }
            else
            {
                data.TenNV = nv.TenNV;
                data.email = nv.email;
                data.GioiTinh = nv.GioiTinh;
                data.Matkhau = nv.Matkhau;
                context.SubmitChanges();
                return RedirectToAction(nameof(QuanLyNV_GD));

            }

        }


        public ActionResult Delete(int id)
        {
            var nv = context.NVPDTs.ToList().Find(m => m.MaNV == id);
            return View(nv);
        }


        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var nv = context.NVPDTs.ToList().Find(m => m.MaNV == id);
            if (nv != null)
            {
                context.NVPDTs.DeleteOnSubmit(nv);
                context.SubmitChanges();
                return RedirectToAction(nameof(QuanLyNV_GD));
            }
            return View(nv);
        }
    }
}

Project/OODWebsite/OODWebsite/Areas/QuanLyHeThong/Views/QuanLyNV_GD/Create.cshtml
@model OODWebsite.NVPDT

@{
    ViewBag.Title = "Quản lý nhân viên";
    Layout = "~/Areas/QuanLyHeThong/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thêm tài khoản</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Tên nhân viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Giới tính", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Mật khẩu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Matkhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Matkhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </div>

    </div>

    <div class="pl-4">
        @Html.ActionLink("Hủy", "QuanLyNV_GD", null, new { @class = "btn btn-default" })
    </div>
}

Project/OODWebsite/OODWebsite/Areas/QuanLyHeThong/Views/QuanLyNV_GD/Delete.cshtml
@model OODWebsite.NVPDT

@{
    ViewBag.Title = "Quản lý nhân viên";
    Layout = "~/Areas/QuanLyHeThong/Views/Shared/_Layout.cshtml";
}

@*<h3>Are you sure you want to delete this?</h3>*@
<div class="Delete_nv">
    <h4>Xóa tài khoản</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Tên nhân viên")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>
            @Html.DisplayName("Giới tính")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayName("Email")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayName("Mật khẩu")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Matkhau)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-primary" /> 
             @Html.ActionLink("Hủy", "QuanLyNV_GD", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

Project/OODWebsite/OODWebsite/Areas/QuanLyHeThong/Views/QuanLyNV_GD/Edit.cshtml
@model OODWebsite.NVPDT

@{
    ViewBag.Title = "Quản lý nhân viên";
    Layout = "~/Areas/QuanLyHeThong/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Chỉnh sửa tài khoản</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaNV)

    <div class="form-group">
        @Html.Label("Tên nhân viên", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Giới tính", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Mật khẩu", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Matkhau, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Matkhau, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-primary" />
        </div>
    </div>
</div>

<div class="pl-4">
    @Html.ActionLink("Hủy", "QuanLyNV_GD", null, new { @class = "btn btn-default" })
</div>
}

Project/OODWebsite/OODWebsite/Areas/QuanLyHeThong/Views/QuanLyNV_GD/QuanLyNV_GD.cshtml
@model IEnumerable<OODWebsite.NVPDT>

@{
    ViewBag.Title = "Quản lý nhân viên";
    Layout = "~/Areas/QuanLyHeThong/Views/Shared/_Layout.cshtml";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>QUẢN LÝ NHÂN VIÊN</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href='@Url.Action("QuanLyNV_GD", "QuanLyNV_GD")'>Home</a></li>
                    <li class="breadcrumb-item active">Quản lý nhân viên</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<div class="pl-4 pb-4">
    @Html.ActionLink("Thêm", "Create", null, new { @class = "btn btn-default" })
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Tên nhân viên")
        </th>
        <th>
            @Html.DisplayName("Giới tính")
        </th>
        <th>
            @Html.DisplayName("Email")
        </th>
        <th>
            @Html.DisplayName("Mật khẩu")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TenNV)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GioiTinh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Matkhau)
        </td>
        <td>
            @Html.ActionLink("Sửa", "Edit", null, new { id = item.MaNV }, new { @class = "btn btn-default" })

            @Html.ActionLink("Xóa", "Delete", null, new { id = item.MaNV }, new { @class = "btn btn-default" })
            
        </td>
    </tr>
}

</table>