Project/OODWebsite/OODWebsite/Areas/SinhVien/Controllers/ThongTinSV_GDController.cs
using OODWebsite.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace OODWebsite.Areas.SinhVien.Controllers
{
    public class ThongTinSV_GDController : Controller
    {
        PortalDBDataContext db = new PortalDBDataContext();
        string strConString = "Data Source=DESKTOP-D9VTUH2\\SQLEXPRESS;Initial Catalog=CsdlPortal;Integrated Security=True";

        // GET: SinhVien/ThongTinSV_GD
        public ActionResult ThongTinSV_GD()
        {
            using (var cn = new SqlConnection(strConString))
            {
                String sql = "SELECT SV.MSSV, SV.HoTen, SV.GioiTinh,\r\n\t\tSV.NgaySinh, SV.MatKhau, SV.KhoaHoc,\r\n\t\tCT.TenCTDT, K.TenKhoa, SV.Id\r\nFROM SINHVIEN AS SV\r\nINNER JOIN CTDAOTAO AS CT ON SV.MaCTDT = CT.MaCTDT\r\nINNER JOIN LOP AS L ON SV.MaLop = L.MaLop\r\nINNER JOIN KHOA AS K ON L.MaSoKhoa = K.MaSoKhoa";
                SqlCommand cmd = new SqlCommand(sql, cn);
                cn.Open();
                SqlDataReader rdr = cmd.ExecuteReader();
                List<SV> model = new List<SV>();
                while (rdr.Read())
                {
                    var details = new SV();
                    details.ID = Convert.ToInt32(rdr["Id"].ToString());
                    details.MSSV = rdr["MSSV"].ToString();
                    details.HoTen = rdr["HoTen"].ToString();
                    details.GioiTinh = rdr["GioiTinh"].ToString();
                    details.NgaySinh = Convert.ToDateTime(rdr["NgaySinh"].ToString());
                    details.MatKhau = rdr["MatKhau"].ToString();
                    details.TenCTDT = rdr["TenCTDT"].ToString();
                    details.KhoaHoc = Convert.ToInt32(rdr["KhoaHoc"].ToString());
                    details.Khoa = rdr["TenKhoa"].ToString();
                    model.Add(details);
                }

                HttpCookie nameCookie = Request.Cookies["SV_ID"];
                string mssv = nameCookie.Values["SV_ID"];
                var sv = model.Find(m=>m.MSSV == mssv);
                return View(sv);
            }
        }

        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string MatKhauHienTai, string MatKhauMoi, string MatKhauMoi2)
        {
            HttpCookie nameCookie = Request.Cookies["SV_ID"];
            string mssv = nameCookie.Values["SV_ID"];
            var sv = db.SINHVIENs.ToList().Find(m => m.MSSV == mssv);
            if(sv.MatKhau != MatKhauHienTai && MatKhauHienTai!= "")
            {
                ModelState.AddModelError("", "Mật khẩu hiện tại không đúng");
                return View();
            }
            else if(MatKhauMoi == "" || MatKhauHienTai == "")
            {
                ModelState.AddModelError("", "Thiếu thông tin");
                return View();
            }
            else if(MatKhauMoi == MatKhauHienTai)
            {
                ModelState.AddModelError("", "Mật khẩu mới giống với mật khẩu cũ");
                return View();
            }
            else if(MatKhauMoi != MatKhauMoi2)
            {
                ModelState.AddModelError("", "Nhập lại mật khẩu mới không đúng");
                return View();
            }
            sv.MatKhau = MatKhauMoi;
            db.SubmitChanges();
            return RedirectToAction(nameof(ThongTinSV_GD));
        }
    }
}

Project/OODWebsite/OODWebsite/Areas/SinhVien/Views/ThongTinSV_GD/Edit.cshtml
@{
    ViewBag.Title = "Đổi mật khẩu";
    Layout = "~/Areas/SinhVien/Views/Shared/_Layout.cshtml";
}

<div class="content ">
    <div class="card card-user">
        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="card-header">
                    <h5 class="card-title">ĐỔI MẬT KHẨU</h5>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-black" })
                <table>
                    <tbody class="row">
                        <tr class="pr-1 form-group">
                            <td>Mật khẩu hiện tại</td>
                            <td>@Html.Password("MatKhauHienTai", "", new { @class = "text-black" })</td>
                        </tr>
                        <tr>
                            <td colspan="3" height="5">
                            </td>
                        </tr>
                        <tr class="pr-1 form-group">
                            <td>Mật khẩu mới</td>
                            <td>@Html.Password("MatKhauMoi", "", new { @class = "text-black" })</td>
                        </tr>
                        <tr>
                            <td colspan="3" height="5">
                            </td>
                        </tr>
                        <tr class="pr-1 form-group">
                            <td>Nhập lại mật khẩu</td>
                            <td>@Html.Password("MatKhauMoi2", "", new { @class = "text-blcak" })</td>
                        </tr>
                        <tr>
                            <td><input type="submit" value="Đổi mật khẩu" class="btn btn-primary" /></td>
                            <td>@Html.ActionLink("Hủy", "ThongTinSV_GD", null, new { @class = "btn btn-default" })</td>
                        </tr>
                    </tbody>
                </table>
            }
        </div>
    </div>
</div>

Project/OODWebsite/OODWebsite/Areas/SinhVien/Views/ThongTinSV_GD/ThongTinSV_GD.cshtml
@model OODWebsite.Models.SV
@{
    ViewBag.Title = "ThongTinSV_GD";
    Layout = "~/Areas/SinhVien/Views/Shared/_Layout.cshtml";
}

<div class="content ">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-user">
                <div class="card-header">
                    <h5 class="card-title">THÔNG TIN SINH VIÊN</h5>
                </div>
                <div class="card-body">
                    <form>
                        <div class="row">
                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    <label>MSSV: </label>
                                    @Html.DisplayFor(model => model.MSSV)
                                </div>
                            </div>
                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    <label>Bậc đào tạo: </label>
                                    @Html.DisplayFor(model => model.TenCTDT)
                                </div>
                            </div>
                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    <label>Họ và tên: </label>
                                    @Html.DisplayFor(model => model.HoTen)
                                </div>
                            </div>
                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    <label>Khoa: </label>
                                    @Html.DisplayFor(model => model.Khoa)
                                </div>
                            </div>
                            <div class="col-md-6 pl-1">
                                <div class="form-group">
                                    <label>Giới tính: </label>
                                    @Html.DisplayFor(model => model.GioiTinh)
                                </div>
                            </div>
                            <div class="col-md-6 pl-1">
                                <div class="form-group">
                                    <label>Ngày sinh: </label>
                                    @Html.DisplayFor(model => model.NgaySinh)
                                </div>
                            </div>
                            <div class="col-md-6 pl-1">
                                <div class="form-group">
                                    <label>Khóa học: </label>
                                    @Html.DisplayFor(model => model.KhoaHoc)
                                </div>
                            </div>
                        </div>
                        @Html.ActionLink("Đổi mật khẩu", "Edit", null, new { @class = "btn btn-default" })
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>