Project/OODWebsite/OODWebsite/Areas/NVPhongDaoTao/Controllers/DanhSachHP_GDController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OODWebsite.Models;

namespace OODWebsite.Areas.NVPhongDaoTao.Controllers
{
    public class DanhSachHP_GDController : Controller
    {
        PortalDBDataContext db = new PortalDBDataContext();

        // GET: NVPhongDaoTao/DanhSachHP_GD
        public ActionResult DanhSachHP_GD()
        {
            var model = db.HOCPHANs.ToList();
            return View(model);
            
        }
        public ActionResult Create()
        {
            ViewBag.Khoa = new SelectList(db.KHOAs, "MaSoKhoa", "TenKhoa");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "Id")] HOCPHAN hp)
        {
            if (ModelState.IsValid)
            {
                db.HOCPHANs.InsertOnSubmit(hp);
                db.SubmitChanges();
                return RedirectToAction(nameof(DanhSachHP_GD));
            }
            ViewBag.Khoa = new SelectList(db.KHOAs, "MaSoKhoa", "TenKhoa");
            return View(hp);
        }

        public ActionResult Edit(int id)
        {
            var hp = db.HOCPHANs.ToList().Find(m => m.MSHP == id);
            return View(hp);
        }


        [HttpPost]
        public ActionResult Edit(HOCPHAN hp)
        {
            var data = db.HOCPHANs.ToList().Find(m => m.MSHP == hp.MSHP);
            if (ModelState.IsValid)
            {
                data.TenHP = hp.TenHP;
                data.SoTinChi = hp.SoTinChi;
                data.MaSoKhoa = hp.MaSoKhoa;
                data.TuyenQuyet = hp.TuyenQuyet;
                db.SubmitChanges();
                return RedirectToAction(nameof(DanhSachHP_GD));
            }
            ViewBag.Khoa = new SelectList(db.KHOAs, "MaSoKhoa", "TenKhoa");
            return View(hp);
        }


        public ActionResult Delete(int id)
        {
            var hp = db.HOCPHANs.ToList().Find(m => m.MSHP == id);
            return View(hp);
        }


        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var hp = db.HOCPHANs.ToList().Find(m => m.MSHP == id);
            if (hp != null)
            {
                db.HOCPHANs.DeleteOnSubmit(hp);
                db.SubmitChanges();
                return RedirectToAction(nameof(DanhSachHP_GD));
            }
            return View(hp);
        }
    }
}

Project/OODWebsite/OODWebsite/Areas/NVPhongDaoTao/Views/DanhSachHP_GD/Create.cshtml
@model OODWebsite.HOCPHAN

@{
    ViewBag.Title = "Thêm học phần";
    Layout = "~/Areas/NVPhongDaoTao/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thêm học phần</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Mã học phần", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaHP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaHP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tên học phần", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenHP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Số tín chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoTinChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoTinChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Khoa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaSoKhoa", ViewBag.Khoa as SelectList, "Chọn Khoa", new { @class = "text-black" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tuyên quyết", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TuyenQuyet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TuyenQuyet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </div>

    </div>

    <div class="pl-4">
        @Html.ActionLink("Hủy", "DanhSachHP_GD", null, new { @class = "btn btn-default" })
    </div>
}

Project/OODWebsite/OODWebsite/Areas/NVPhongDaoTao/Views/DanhSachHP_GD/DanhSachHP_GD.cshtml
@model IEnumerable<OODWebsite.HOCPHAN>

@{
    ViewBag.Title = "Danh sách học phần";
    Layout = "~/Areas/NVPhongDaoTao/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>DANH SÁCH HỌC PHẦN</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href='@Url.Action("QuanLySV_GD", "QuanLySV_GD")'>Home</a></li>
                    <li class="breadcrumb-item active">Danh sách học phần</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<div class="pl-4 pb-4">
    @Html.ActionLink("Thêm", "Create", null, new { @class = "btn btn-default" })
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Mã học phần")
        </th>
        <th>
            @Html.DisplayName("Tên học phần")
        </th>
        <th class="text-center">
            @Html.DisplayName("Số tín chỉ")
        </th>
        <th class="text-center">
            @Html.DisplayName("Mã số khoa")
        </th>
        <th>
            @Html.DisplayName("Tuyên quyết")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaHP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenHP)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.SoTinChi)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.MaSoKhoa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TuyenQuyet)
            </td>
            <td>

                @Html.ActionLink("Sửa", "Edit", null, new { id = item.MSHP }, new { @class = "btn btn-default" })

                @Html.ActionLink("Xóa", "Delete", null, new { id = item.MSHP }, new { @class = "btn btn-default" })
            </td>
        </tr>
    }

</table>

Project/OODWebsite/OODWebsite/Areas/NVPhongDaoTao/Views/DanhSachHP_GD/Delete.cshtml
@model OODWebsite.HOCPHAN

@{
    ViewBag.Title = "Danh sách học phần";
    Layout = "~/Areas/NVPhongDaoTao/Views/Shared/_Layout.cshtml";
}

@*<h3>Are you sure you want to delete this?</h3>*@
<div class="Delete_hp">
    <h4>Xóa học phhần</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Mã học phần")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaHP)
        </dd>

        <dt>
            @Html.DisplayName("Tên học phần")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHP)
        </dd>

        <dt>
            @Html.DisplayName("Số tín chỉ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoTinChi)
        </dd>

        <dt>
            @Html.DisplayName("Mã số khoa")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSoKhoa)
        </dd>

        <dt>
            @Html.DisplayName("Tuyên quyết")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TuyenQuyet)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Xóa" class="btn btn-primary" />
            @Html.ActionLink("Hủy", "DanhSachHP_GD", null, new { @class = "btn btn-default" })
        
    </div>
    }
</div>

Project/OODWebsite/OODWebsite/Areas/NVPhongDaoTao/Views/DanhSachHP_GD/Edit.cshtml
@model OODWebsite.HOCPHAN

@{
    ViewBag.Title = "Danh sách học phần";
    Layout = "~/Areas/NVPhongDaoTao/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Chỉnh sửa học phần</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MSHP)

        <div class="form-group">
            @Html.Label("Mã học phần", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaHP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaHP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tên học phần", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenHP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Số tín chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoTinChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoTinChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Mã số khoa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSoKhoa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaSoKhoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tuyên quyết", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TuyenQuyet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TuyenQuyet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </div>


    </div>

    <div class="pl-4">
        @Html.ActionLink("Hủy", "DanhSachHP_GD", null, new { @class = "btn btn-default" })
    </div>
    
}